#ifndef STATISTICSMODULES_GLOBAL_H
#define STATISTICSMODULES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STATISTICSMODULES_LIBRARY)
#  define STATISTICSMODULESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define STATISTICSMODULESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // STATISTICSMODULES_GLOBAL_H
