//<LICENSE>

#ifndef MODULECONFIG_GLOBAL_H
#define MODULECONFIG_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODULECONFIG_LIBRARY)
#  define MODULECONFIGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MODULECONFIGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MODULECONFIG_GLOBAL_H
