#ifndef READERCONFIG_GLOBAL_H
#define READERCONFIG_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(READERCONFIG_LIBRARY)
#  define READERCONFIGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define READERCONFIGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // READERCONFIG_GLOBAL_H
