#ifndef ITERATIVEBACKPROJ_GLOBAL_H
#define ITERATIVEBACKPROJ_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ITERATIVEBACKPROJ_LIBRARY)
#  define ITERATIVEBACKPROJSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ITERATIVEBACKPROJSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GENERICBACKPROJ_GLOBAL_H
