stages:
  - build

debS_clang:
  tags: &unix
  - Linux
  image: debian:stable
  before_script: &debian_clang
    - apt-get -y update
    - apt-get -y upgrade
    - apt-get -y install cmake perl
    - apt-get -y install clang
  stage: build
  script: &scr
    - mkdir build
    - cd build
    - cmake -DWERROR=ON ..
    - make
    - ctest --output-on-failure

debS_gcc:
  tags: *unix
  image: debian:stable
  before_script: &debian_gcc
    - apt-get -y update
    - apt-get -y upgrade
    - apt-get -y install cmake perl
    - apt-get -y install gcc
  stage: build
  script: *scr

debT_clang:
  tags: *unix
  image: debian:testing
  before_script: *debian_clang
  stage: build
  script: *scr

debT_gcc:
  tags: *unix
  image: debian:testing
  before_script: *debian_gcc
  stage: build
  script: *scr

debU_clang:
  tags: *unix
  image: debian:unstable
  before_script: *debian_clang
  stage: build
  script: *scr

debU_gcc:
  tags: *unix
  image: debian:unstable
  before_script: *debian_gcc
  stage: build
  script: *scr

suse_clang:
  tags: *unix
  image: opensuse/tumbleweed
  # rolling release with infinite life time
  before_script:
    - zypper -n patch || echo "do it again"
    - zypper -n patch
    - zypper -n ref
    - zypper -n up
    - zypper -n dup
    - zypper -n in cmake perl
    - zypper -n in clang gcc glibc-devel
    - export CC=/usr/bin/clang
  stage: build
  script: *scr

suse_gcc:
  tags: *unix
  image: opensuse/tumbleweed
  # rolling release with infinite life time
  before_script:
    - zypper -n patch || echo "do it again"
    - zypper -n patch
    - zypper -n ref
    - zypper -n up
    - zypper -n dup
    - zypper -n in cmake perl
    - zypper -n in gcc
  stage: build
  script: *scr

# suse_stable:
#  opensuse:leap, unsupported here because it is at cmake 3.5, while libcerf requires 3.6

centos7_clang:
  tags: *unix
  image: centos:centos7
  before_script:
    - yum -y update
    - yum -y install epel-release
    - yum repolist
    - yum -y install make cmake3 perl
    - yum -y install clang gcc glibc-devel
    - export CC=/usr/bin/clang
    - cmake3 --version
    - ctest3 --version
    - cpack3 --version
    - ln -s /usr/bin/cmake3 /usr/bin/cmake
    - ln -s /usr/bin/ctest3 /usr/bin/ctest
    - ln -s /usr/bin/cpack3 /usr/bin/cpack
  stage: build
  script: *scr

centos7_gcc:
  tags: *unix
  image: centos:centos7
  before_script:
    - yum -y update
    - yum -y install epel-release
    - yum repolist
    - yum -y install make cmake3 perl
    - yum -y install gcc
    - cmake3 --version
    - ctest3 --version
    - cpack3 --version
    - ln -s /usr/bin/cmake3 /usr/bin/cmake
    - ln -s /usr/bin/ctest3 /usr/bin/ctest
    - ln -s /usr/bin/cpack3 /usr/bin/cpack
  stage: build
  script: *scr

windows:
  tags:
  - Windows
  stage: build
  script:
    - New-Item -ItemType "directory" -Confirm:$false -Force:$true -Name "build"
    - cd build
    - cmd.exe "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
    - cmake -G "Visual Studio 15 2017" -A x64 -T host=x64 -DLIB_MAN=OFF -DLIB_INSTALL=OFF -B. ..
    - cmake --build . --config Release
    - Get-Location
    - dir
    - dir Release
    - ctest -C Release --output-on-failure
