#ifndef IMAGINGQAALGORITHMS_GLOBAL_H
#define IMAGINGQAALGORITHMS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(IMAGINGQAALGORITHMS_LIBRARY)
#  define IMAGINGQAALGORITHMSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define IMAGINGQAALGORITHMSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // IMAGINGQAALGORITHMS_GLOBAL_H
