#!/bin/sh

RP="`readlink -e $0`"
BASEPATH="`dirname $RP`"

KIPTOOL_BASE_PATH=$BASEPATH
LD_LIBRARY_PATH=$BASEPATH/Frameworks:$LD_LIBRARY_PATH
export KIPTOOL_BASE_PATH
export LD_LIBRARY_PATH

args="";
for arg in $*;
do
	args=$args" "$arg
done

$BASEPATH/bin/KipTool $args

