#ifndef UNPUBLPREPROCESSINGGUI_GLOBAL_H
#define UNPUBLPREPROCESSINGGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UNPUBLPREPROCESSINGGUI_LIBRARY)
#  define UNPUBLPREPROCESSINGGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define UNPUBLPREPROCESSINGGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UNPUBLPREPROCESSINGGUI_GLOBAL_H
