[workspace]
authors = ["Anders Kaestner <anders.kaestner@psi.ch>"]
channels = ["conda-forge"]
name = "scripts"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
numpy = "*"
scipy = "*"
matplotlib = "*"
jupyter = "*"
pandas = "*"
scikit-learn = "*"
scikit-image = "*"
uncertainties = "*"
ipywidgets = "*"
astropy = "*"
tifffile = "*"
tqdm = "*"
pytest = "*"
pybind11 = "*"
jupyter_contrib_nbextensions = "*"
