[workspace]
authors = ["Anders Kaestner <anders.kaestner@psi.ch>"]
channels = ["conda-forge"]
name = "scripts"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"
numpy = ">=2.3.5,<3"
scipy = ">=1.16.3,<2"
matplotlib = ">=3.10.8,<4"
jupyter = ">=1.1.1,<2"
notebook = ">=6.5.7,<7"
pandas = ">=2.3.3,<3"
scikit-learn = ">=1.8.0,<2"
scikit-image = ">=0.25.2,<0.26"
uncertainties = ">=3.2.3,<4"
ipywidgets = ">=8.1.8,<9"
astropy = ">=7.2.0,<8"
tifffile = ">=2025.12.12,<2026"
tqdm = ">=4.67.1,<5"
pytest = ">=9.0.2,<10"
pybind11 = ">=3.0.1,<4"
jupyter_contrib_nbextensions = ">=0.7.0,<0.8"
