[workspace]
authors = ["Anders Kaestner <anders.kaestner@psi.ch>"]
channels = ["conda-forge"]
name = "scripts"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = "*"
scipy = "*"
matplotlib = "*"
jupyter = "*"
notebook = "6.*"
pandas = "*"
scikit-learn = "*"
scikit-image = "*"
uncertainties = "*"
opencv = "*"
pandoc = "*"
jupyter-book = "*"
ipywidgets = "*"
astropy = "*"
dask = "*"
mysqlclient = "*"
seaborn = "*"
tifffile = "*"
tqdm = "*"
pytest = "*"
matplotlib-scalebar = "*"
ffmpeg = "*"
rise = "*"
jupyter_contrib_nbextensions = "*"