#ifndef UNPUBLISHEDMODULES_GLOBAL_H
#define UNPUBLISHEDMODULES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UNPUBLISHEDMODULES_LIBRARY)
#  define UNPUBLISHEDMODULESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UNPUBLISHEDMODULESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UNPUBLISHEDMODULES_GLOBAL_H
