#ifndef RECONALGORITHMS_GLOBAL_H
#define RECONALGORITHMS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RECONALGORITHMS_LIBRARY)
#  define RECONALGORITHMSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RECONALGORITHMSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RECONALGORITHMS_GLOBAL_H
