#ifndef CLASSIFICATIONMODULES_GLOBAL_H
#define CLASSIFICATIONMODULES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CLASSIFICATIONMODULES_LIBRARY)
#  define CLASSIFICATIONMODULES_EXPORT Q_DECL_EXPORT
#else
#  define CLASSIFICATIONMODULES_EXPORT Q_DECL_IMPORT
#endif

#endif // CLASSIFICATIONMODULES_GLOBAL_H
