//<LICENSE>

#ifndef GENERICPREPROC_GLOBAL_H
#define GENERICPREPROC_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GENERICPREPROC_LIBRARY)
#  define GENERICPREPROCSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GENERICPREPROCSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GENERICPREPROC_GLOBAL_H
