#ifndef ADVANCEDFILTERMODULESGUI_GLOBAL_H
#define ADVANCEDFILTERMODULESGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ADVANCEDFILTERMODULESGUI_LIBRARY)
#  define ADVANCEDFILTERMODULESGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define ADVANCEDFILTERMODULESGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ADVANCEDFILTERMODULESGUI_GLOBAL_H
