//<LICENSE>

#ifndef QTMODULECONFIGURE_GLOBAL_H
#define QTMODULECONFIGURE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTMODULECONFIGURE_LIBRARY)
#  define QTMODULECONFIGURESHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTMODULECONFIGURESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTMODULECONFIGURE_GLOBAL_H
