#ifndef CLASSIFICATIONMODULESGUI_GLOBAL_H
#define CLASSIFICATIONMODULESGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CLASSIFICATIONMODULESGUI_LIBRARY)
#  define CLASSIFICATIONMODULESGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define CLASSIFICATIONMODULESGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CLASSIFICATIONMODULESGUI_GLOBAL_H
