//<LICENSE>

#ifndef FDKBACKPROJ_GLOBAL_H
#define FDKBACKPROJ_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FDKBACKPROJ_LIBRARY)
#  define FDKBACKPROJSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FDKBACKPROJSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FDKBACKPROJ_GLOBAL_H
