//<LICENSE>

#ifndef GENERICBACKPROJ_GLOBAL_H
#define GENERICBACKPROJ_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GENERICBACKPROJ_LIBRARY)
#  define GENERICBACKPROJSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GENERICBACKPROJSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GENERICBACKPROJ_GLOBAL_H
