#!/bin/sh
comm="valgrind --leak-check=full --show-reachable=yes --leak-resolution=high --num-callers=40"
echo ">>> Running valgrind on \"leak_test1\" - results sent to \"leak_test1.log\""
$comm --log-file-exactly=leak_test1.log ./leak_test1
echo ">>> Test1 done"
echo " "
echo ">>> Running valgrind on \"leak_test2\" - results sent to \"leak_test2.log\""
$comm --log-file-exactly=leak_test2.log ./leak_test2
echo ">>> Test2 done"
echo " "
echo ">>> Running valgrind on \"leak_test3\" - results sent to \"leak_test3.log\""
$comm --log-file-exactly=leak_test3.log ./leak_test3
echo ">>> Test3 done"
