#ifndef IMAGINGMODULES_GLOBAL_H
#define IMAGINGMODULES_GLOBAL_H
#include <QtCore/qglobal.h>

#if defined(IMAGINGMODULES_LIBRARY)
#  define IMAGINGMODULESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define IMAGINGMODULESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // IMAGINGMODULES_GLOBAL_H
