#ifndef UNPUBLPREPROCESSING_GLOBAL_H
#define UNPUBLPREPROCESSING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UNPUBLPREPROCESSING_LIBRARY)
#  define UNPUBLPREPROCESSINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UNPUBLPREPROCESSINGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UNPUBLPREPROCESSING_GLOBAL_H
