#ifndef PORESPACEMODULES_GLOBAL_H
#define PORESPACEMODULES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PORESPACEMODULES_LIBRARY)
#  define PORESPACEMODULES_EXPORT Q_DECL_EXPORT
#else
#  define PORESPACEMODULES_EXPORT Q_DECL_IMPORT
#endif

#endif // PORESPACEMODULES_GLOBAL_H
