#ifndef UNPUBLISHEDMODULESGUI_GLOBAL_H
#define UNPUBLISHEDMODULESGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UNPUBLISHEDMODULESGUI_LIBRARY)
#  define UNPUBLISHEDMODULESGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define UNPUBLISHEDMODULESGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UNPUBLISHEDMODULESGUI_GLOBAL_H
