#ifndef UNPUBLISHEDIMAGINGALGORITHMS_GLOBAL_H
#define UNPUBLISHEDIMAGINGALGORITHMS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UNPUBLISHEDIMAGINGALGORITHMS_LIBRARY)
#  define UNPUBLISHEDIMAGINGALGORITHMSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UNPUBLISHEDIMAGINGALGORITHMSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UNPUBLISHEDIMAGINGALGORITHMS_GLOBAL_H
