//<LICENSE>

#ifndef INSPECTORMODULESGUI_GLOBAL_H
#define INSPECTORMODULESGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(INSPECTORMODULESGUI_LIBRARY)
#  define INSPECTORMODULESGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define INSPECTORMODULESGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // INSPECTORMODULESGUI_GLOBAL_H
