#ifndef ADVANCEDFILTERMODULES_GLOBAL_H
#define ADVANCEDFILTERMODULES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ADVANCEDFILTERMODULES_LIBRARY)
#  define ADVANCEDFILTERMODULES_EXPORT Q_DECL_EXPORT
#else
#  define ADVANCEDFILTERMODULES_EXPORT Q_DECL_IMPORT
#endif

#endif // ADVANCEDFILTERMODULES_GLOBAL_H
