#ifndef BASEMODULESGUI_GLOBAL_H
#define BASEMODULESGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BASEMODULESGUI_LIBRARY)
#  define BASEMODULESGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define BASEMODULESGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BASEMODULESGUI_GLOBAL_H
