#ifndef RECONFRAMEWORK_GLOBAL_H
#define RECONFRAMEWORK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RECONFRAMEWORK_LIBRARY)
#  define RECONFRAMEWORKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RECONFRAMEWORKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RECONFRAMEWORK_GLOBAL_H
