//<LICENSE>

#ifndef INSPECTORMODULES_GLOBAL_H
#define INSPECTORMODULES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(INSPECTORMODULES_LIBRARY)
#  define INSPECTORMODULESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define INSPECTORMODULESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // INSPECTORMODULES_GLOBAL_H
