# This workflow creates a release and uploads pymuhrec to pypi whenever a new tag is pushed to the repository.
name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  Run_build_workflow:
    uses: ./.github/workflows/Build-multi-OS.yml

  Create_release:
    needs: Run_build_workflow
    runs-on: ubuntu-latest
        
    steps:
        - name: Download MuhRec application artifacts
          uses: dawidd6/action-download-artifact@v6
          with:
            github_token: ${{secrets.GITHUB_TOKEN}}
            workflow: Build-multi-OS.yml
            workflow_conclusion: success
            branch: master

        - name: Recompress applications
          shell: bash
          run: |
            zip -r MuhRec-Linux-X64.zip MuhRec-Linux-X64/*
            zip -r MuhRec-Windows-X64.zip MuhRec-Windows-X64/*
            zip -r MuhRec-macOS-ARM64.zip MuhRec-macOS-ARM64/*
            zip -r MuhRec-macOS-X64.zip MuhRec-macOS-X64/*

        - name: Download pymuhrec wheels
          uses: dawidd6/action-download-artifact@v6
          with:
            github_token: ${{secrets.GITHUB_TOKEN}}
            workflow: Build-wheels.yml
            workflow_conclusion: success
            branch: master

        - name: Create Release and upload artifacts
          uses: softprops/action-gh-release@v2
          with:
            files: |
              pymuhrec-*/*.whl
              MuhRec-*